apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"snippets-dev"},"name":"snippets-nodeport","namespace":"snippets-dev"},"spec":{"ports":[{"name":"http","port":80,"targetPort":8000}],"selector":{"app":"snippets-dev","type":"web"},"type":"NodePort"}}
  creationTimestamp: "2018-08-06T14:25:32Z"
  labels:
    app: snippets-dev
  name: snippets-nodeport
  namespace: snippets-dev
  resourceVersion: "45842717"
  selfLink: /api/v1/namespaces/snippets-dev/services/snippets-nodeport
  uid: 937fcc74-9984-11e8-8eeb-0656fabf84c0
spec:
  clusterIP: 100.67.208.101
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30098
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: snippets-dev
    type: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
