apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: snippets-dev
  name: snippets-nodeport
  namespace: snippets-dev
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30098
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: snippets-dev
    type: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
