apiVersion: v1
kind: Service
metadata:
  name: snippets-prod
  namespace: snippets-prod
  labels:
    run: snippets-prod
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:236517346949:certificate/5514f163-47e2-4a2c-afe1-4af5d3bdb7f9
     external-dns.alpha.kubernetes.io/hostname: snippets-prod.oregon-b.moz.works.
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 8000
    protocol: TCP
  selector:
    app: snippets-prod
