apiVersion: v1
kind: Service
metadata:
  name: snippets-dev
  labels:
    app: snippets-dev
  namespace: snippets-dev
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
     service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:236517346949:certificate/34e80874-09dd-4baa-b544-72d0aa630794"
     external-dns.alpha.kubernetes.io/hostname: "snippets-dev.oregon-b.moz.works,dev.snippets.moz.works"
spec:
  type: LoadBalancer
  ports:
  - port: 443
    name: https
    targetPort: 8000
    protocol: TCP
  - port: 80
    name: http
    targetPort: 8000
    protocol: TCP
  selector:
    app: snippets-dev
    type: web
