apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: snippets-prod
  namespace: snippets-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: snippets-prod
  minReplicas: 5
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 85
