apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"snippets-stage"},"name":"snippets-nodeport","namespace":"snippets-stage"},"spec":{"ports":[{"name":"https","port":443,"targetPort":8000}],"selector":{"app":"snippets-stage","type":"web"},"type":"NodePort"}}
  creationTimestamp: "2018-02-07T14:10:22Z"
  labels:
    app: snippets-stage
  name: snippets-nodeport
  namespace: snippets-stage
  resourceVersion: "3685482"
  selfLink: /api/v1/namespaces/snippets-stage/services/snippets-nodeport
  uid: a2856fce-0c10-11e8-8c8b-0656fabf84c0
spec:
  clusterIP: 100.64.197.1
  externalTrafficPolicy: Cluster
  ports:
  - name: https
    nodePort: 30586
    port: 443
    protocol: TCP
    targetPort: 8000
  selector:
    app: snippets-stage
    type: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
