apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: snippets-stage
  name: snippets-nodeport
  namespace: snippets-stage
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: https
    nodePort: 30586
    port: 443
    protocol: TCP
    targetPort: 8000
  selector:
    app: snippets-stage
    type: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
