---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: snippets-stage-secrets
  namespace: snippets-stage
spec:
  backendType: secretsManager
  region: us-west-2
  data:
    - key: mozmeao/snippets/stage/aws_access_key_id
      name: aws-access-key-id
    - key: mozmeao/snippets/stage/aws_secret_access_key
      name: aws-secret-access-key
    - key: mozmeao/snippets/stage/cache_url
      name: cache-url
    - key: mozmeao/snippets/stage/database_url
      name: database-url
    - key: mozmeao/snippets/stage/dead_mans_snitch_update_jobs
      name: dead-mans-snitch-update-jobs
    - key: mozmeao/snippets/stage/dead_mans_snitch_product_details
      name: dead-mans-snitch-product-details
    - key: mozmeao/snippets/stage/new_relic_license_key
      name: new-relic-license-key
    - key: mozmeao/snippets/stage/oidc_rp_client_id
      name: oidc-rp-client-id
    - key: mozmeao/snippets/stage/oidc_rp_client_secret
      name: oidc-rp-client-secret
    - key: mozmeao/snippets/stage/secret_key
      name: secret-key
    - key: mozmeao/snippets/stage/sentry_dsn
      name: sentry-dsn
    - key: mozmeao/snippets/stage/slack_webhook
      name: slack-webhook
