apiVersion: v1
kind: Service
metadata:
  name: snippets-stage
  namespace: snippets-stage
  labels:
    run: snippets-stage
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:236517346949:certificate/6c8ca0be-8082-4587-9f19-42db2603d593
     external-dns.alpha.kubernetes.io/hostname: snippets-stage.oregon-b.moz.works.
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 8000
    protocol: TCP
  selector:
    app: snippets-stage
