apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: snippets-admin
  name: snippets-admin-nodeport
  namespace: snippets-prod
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 31204
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: snippets-admin
    type: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
