apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"snippets-prod"},"name":"snippets-nodeport","namespace":"snippets-prod"},"spec":{"ports":[{"name":"http","port":80,"targetPort":8000}],"selector":{"app":"snippets-prod","type":"web"},"type":"NodePort"}}
  creationTimestamp: "2018-04-10T15:51:40Z"
  labels:
    app: snippets-prod
  name: snippets-nodeport
  namespace: snippets-prod
  resourceVersion: "16818884"
  selfLink: /api/v1/namespaces/snippets-prod/services/snippets-nodeport
  uid: 0f5e800d-3cd7-11e8-8eeb-0656fabf84c0
spec:
  clusterIP: 100.71.62.189
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32423
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: snippets-prod
    type: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
