apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: snippets-admin
  namespace: snippets-admin
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: snippets-admin
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 85
