apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: snippets-admin
    type: web
  name: snippets-admin
  namespace: snippets-admin
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: snippets-admin
      type: web
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: snippets-admin
        type: web
      name: snippets-admin
      namespace: snippets-admin
    spec:
      imagePullSecrets:
        - name: dockerhub-registry
      containers:
      - command:
          - ./bin/run-prod.sh
        env:
          - name: ALLOWED_HOSTS
            value: "*"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: aws-access-key-id
                name: snippets-admin-secrets
          - name: AWS_S3_HOST
            value: "s3-us-west-2.amazonaws.com"
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: aws-secret-access-key
                name: snippets-admin-secrets
          - name: AWS_STORAGE_BUCKET_NAME
            value: "snippets-prod-us-west"
          - name: BUNDLE_BROTLI_COMPRESS
            value: "True"
          - name: CACHE_URL
            valueFrom:
              secretKeyRef:
                key: cache-url
                name: snippets-admin-secrets
          - name: CDN_URL
            value: https://snippets.cdn.mozilla.net
          - name: CLUSTER_NAME
            value: "oregon"
          - name: CSP_REPORT_ENABLE
            value: "False"
          - name: CSP_REPORT_ONLY
            value: "True"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                key: database-url
                name: snippets-admin-secrets
          - name: DEBUG
            value: "False"
          - name: ENABLE_ADMIN
            value: "True"
          - name: ENFORCE_HOST
            value: "snippets-admin.mozilla.org"
          - name: FILE_STORAGE
            value: snippets.base.storage.S3Storage
          - name: MEDIA_BUNDLES_ROOT
            value: us-west/bundles/
          - name: MEDIA_ICONS_ROOT
            value: media/icons/
          - name: NEW_RELIC_APP_NAME
            value: snippets-admin-oregon-a
          - name: NEW_RELIC_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                key: new-relic-license-key
                name: snippets-admin-secrets
          - name: OIDC_ENABLE
            value: "True"
          - name: OIDC_OP_AUTHORIZATION_ENDPOINT
            value: https://auth.mozilla.auth0.com/authorize
          - name: OIDC_OP_TOKEN_ENDPOINT
            value: https://auth.mozilla.auth0.com/oauth/token
          - name: OIDC_OP_USER_ENDPOINT
            value: https://auth.mozilla.auth0.com/userinfo
          - name: OIDC_RP_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: oidc-rp-client-id
                name: snippets-admin-secrets
          - name: OIDC_RP_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: oidc-rp-client-secret
                name: snippets-admin-secrets
          - name: PROD_DETAILS_STORAGE
            value: product_details.storage.PDDatabaseStorage
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: secret-key
                name: snippets-admin-secrets
          - name: SECURE_BROWSER_XSS_FILTER
            value: "True"
          - name: SECURE_CONTENT_TYPE_NOSNIFF
            value: "True"
          - name: SECURE_HSTS_SECONDS
            value: "31536000"
          - name: SECURE_SSL_REDIRECT
            value: "True"
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                key: sentry-dsn
                name: snippets-admin-secrets
          - name: SENTRY_ENVIRONMENT
            value: prod-admin
          - name: SITE_HEADER
            value: Snippets Administration Production
          - name: SITE_TITLE
            value: Mozilla Snippets Production Admin
          - name: SITE_URL
            value: https://snippets-admin.mozilla.org
          - name: SLACK_ENABLE
            value: "True"
          - name: SLACK_WEBHOOK
            valueFrom:
              secretKeyRef:
                key: slack-webhook
                name: snippets-admin-secrets
          - name: WSGI_KEEP_ALIVE
            value: "90"
          - name: WSGI_NUM_WORKERS
            value: "2"
          - name: MEDIA_BUNDLES_PREGEN_ROOT
            value: us-west/bundles-pregen/
          - name: RATELIMIT_ENABLE
            value: "True"
        image: mozmeao/snippets:9592370e
        imagePullPolicy: IfNotPresent
        name: snippets-admin
        livenessProbe:
          failureThreshold: 4
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
          httpGet:
            path: /healthz/
            scheme: HTTP
            port: 8000
        readinessProbe:
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8000
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 250Mi
          requests:
            cpu: 250m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
